name: DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"

      - name: Print version
        run: echo "VERSION=${{ steps.version.outputs.version }}"

      - name: Build Docker Image
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/devsecops-app:$VERSION \
            -t ghcr.io/${{ github.repository_owner }}/devsecops-app:latest \
            -f app/Dockerfile app/

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Images
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/devsecops-app:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/devsecops-app:latest

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f k8s/

      - name: Wait for Rollout
        run: kubectl rollout status deployment/devsecops-app
